version: '3'
services:
  mysql_db:
    container_name: mysql_db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    image: mysql
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=21830818
      - MYSQL_DATABASE=Bloggy
      - MYSQL_USER=santi1428
      - MYSQL_PASSWORD=21830818
    ports:
      - '3306:3306'
    networks:
      - app-network
  app:
    container_name: bloggy_docker_container
    depends_on:
      - mysql_db
    links:
      - mysql_db
    build: .
    volumes:
      - './php_conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './:/var/www/html/bloggy'
    networks:
      - app-network
  nginx:
    container_name: bloggy_nginx
    restart: unless-stopped
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './:/var/www/html/bloggy'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'  
    networks:
      - app-network
  phpmyadmin:
    container_name: php_my_admin
    depends_on:
      - mysql_db
    image: 'phpmyadmin:latest'
    ports:
      - '8080:80'
    volumes:
      - 'php_my_admin_conf:/etc/phpmyadmin/config.user.inc.php'
    networks:
      - app-network
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
volumes:
  mysql_data:
    driver: local
  php_my_admin_conf:
    driver: local
  nginx_certificates:
    driver: local
networks:
  app-network:
    driver: bridge
