version: '3'
services: 
  mysql_db: 
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql
    volumes: 
      - /mysql_data:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=21830818'
      - 'MYSQL_DATABASE=Bloggy'
      - 'MYSQL_USER=santi1428'
      - 'MYSQL_PASSWORD=21830818'
    ports: 
      - '3306:3306'
    networks:
      - app-network
  app: 
    container_name: bloggy_docker_container
    depends_on:
      - mysql_db
    links:
      - mysql_db
    build: .
    ports:
      - '80:80'
    volumes: 
      - .:/var/www/html/bloggy
    command: > 
      sh -c "php artisan key:generate && ./wait-for-it.sh mysql_db:3306 && 
      php artisan migrate && php artisan passport:install && 
      npm run production && apachectl -D FOREGROUND"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge