version: '3'
services: 
  mysql_db: 
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=21830818'
      - 'MYSQL_DATABASE=Bloggy'
      - 'MYSQL_USER=santi1428'
      - 'MYSQL_PASSWORD=21830818'
    ports: 
      - '3306:3306'
    networks:
      - app-network
  app: 
    container_name: bloggy_docker_container
    restart: always
    depends_on:
      - mysql_db
    build: .
    ports:
      - '80:80'
    volumes: 
      - ./:/var/www/html/bloggy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge